import { Orbitron, Pacifico } from "next/font/google";
import "./style/globals.css";
import { ThemeProvider } from "./context/Theme";

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-orbitron",
});

const pacifico = Pacifico({
  weight: '400', 
  subsets: ['latin'],
  variable: "--font-pacifico",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${pacifico.variable} ${orbitron.className} antialiased`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
